### ISSUE TITLE
SizeMismatch that --max_vocab didn't help

### ISSUE THREAD

**Issue by Dolprimates** [facebookresearch/XLM#108]
I tried unsupervised MT but didn't work.

downloads are through
```
./get-data-nmt.sh --src en --tgt fr
wget https://dl.fbaipublicfiles.com/XLM/codes_enfr
wget https://dl.fbaipublicfiles.com/XLM/vocab_enfr
./get-data-nmt.sh --src en --tgt fr --reload_codes codes_enfr --reload_vocab vocab_enfr
wget -c https://dl.fbaipublicfiles.com/XLM/mlm_enfr_1024.pth
```
the command is
`CUDA_VISIBLE_DEVICES=0 python train.py --exp_name unsupMT_enfr --dump_path ./dumped/ --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path ./data/processed/en-fr/ --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 2000 --batch_size 32 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu' --max_vocab 60375`

the error is
```
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	size mismatch for embeddings.weight: copying a param with shape torch.Size([64139, 1024]) from checkpoint, the shape in current model is torch.Size([60375, 1024]).
	size mismatch for pred_layer.proj.weight: copying a param with shape torch.Size([64139, 1024]) from checkpoint, the shape in current model is torch.Size([60375, 1024]).
	size mismatch for pred_layer.proj.bias: copying a param with shape torch.Size([64139]) from checkpoint, the shape in current model is torch.Size([60375]).
```

removing the option `--max_vocab 60375` gives me the same result.
(python version is 3.6.8.  
Because I heard one of my friends told me that the versions after 3.6.9 didn't work for using tensorflow,  I also tried 3.6.7  for the case python version is the problem)

**Comment by glample** [comment]
Hi,

So the issue is coming from the preprocessing. Since you called `./get-data-nmt.sh --src en --tgt fr` first, without giving the vocabulary, the model probably recomputed the BPE codes. Then when you provided them, the binarized dataset was already there, and calling `./get-data-nmt.sh --src en --tgt fr --reload_codes codes_enfr --reload_vocab vocab_enfr` did not do anything. Can you try to remove the preprocessed data and directly call `./get-data-nmt.sh --src en --tgt fr --reload_codes codes_enfr --reload_vocab vocab_enfr` ?

If this still does not work, please provide the output of that command.

**Comment by Dolprimates** [comment]
Solved the issue. Thanks!!!
