### ISSUE TITLE
Hype-parameter of MLM_TLM_XNLI pre-training

### ISSUE THREAD

**Issue by Eureka6174** [facebookresearch/XLM#119]
Could you please provide a full list of hype-parameter in MLM+TLM pre-training for XNLI 15 languages? Here are several parameters I care most about:
1. The total batch size. total batch size should equal to batch size per GPU times number of GPU. I can't find the number of GPU in your ReadMe.
2. lg_sampling_factor. I think this parameter could influence pre-training speed and XNLI performance a lot. Did you tuned this parameter and what's the best choice based your experiments?
3. How may sentences per GPU did you trained before converge?
4. max_vocab. Why you choose 95K as max vocab? Did it harm the XNLI performance because of the UNK in input?

**Comment by aconneau** [comment]
Hi,

1- batch_size: 32 the maximum that fits on one GPU (*32 or *64 GPUs in our case)
2- lg_sampling_factor = 0.7
3- We trained until convergence of the perplexity, and then kept it training for a bit more time (as valid perplexity is not necessarily well correlated with transferability of the learned representations)
4- max_vocab=95k (after taking 80k BPE splits). I believe there is a trade-off between having a very large-vocabulary (and thus less shared BPE-tokens across languages) and a small one (not enough capacity for the model. That's why we chose ~100k vocab.

**Comment by Eureka6174** [comment]
Hi @aconneau, Thanks to your reply!
For the question 3, now I had understood your training policy. But I'm still curious about the specific time of experiment "XNLI-15 | MLM + TLM". It would be very helpful if you could share the sentences/batch number of this experiment.
For the question 4. For experiment "XNLI-15 | MLM + TLM", I download your vocabulary file and it contains 121K words, but the model only used 95K words. Then the last 26K words become UNK. Will this harm the fine-tuning performance?

**Comment by aconneau** [comment]
For q3: I don't have this number unfortunately. It took around 10 days to train on 64 GPUs.
For q4: you should set the parameter "max-vocab" to 95,000.
