### ISSUE TITLE
Next sentence prediction problem

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/XLM#138]
Why your BERT model achieve better performance than the original BERT without using next sentence prediction?

**Comment by glample** [comment]
Because next sentence prediction forces you to have 2 sentences per sequence in your batch. This is very limitating in practice because it forces you to either have a lot of padding in your batch, or to fit pairs of sentences with similar length. Without this task you can use a stream iterator and fit continuous sequences of text which results in **much** larger batches, and large batches give a better performance.
