### ISSUE TITLE
What is the meaning of binarize dataset?

### ISSUE THREAD

**Issue by Shi-Linqing-Jason** [facebookresearch/XLM#14]

**Comment by aconneau** [comment]
We binarize datasets in particular to reduce memory usage.

**Comment by glample** [comment]
Binarization is convenient because you can compress a large dataset (say 20GB of text) into a single vector in a PyTorch binary file (.pth). The binary file can be loaded in RAM memory in a few seconds which lets you start experiments very quickly.

If the vocabulary size is smaller than 2**16 = 65536 unique words each word is converted to a uint16 integer which is memory efficient.
