### ISSUE TITLE
Handling Multi-Node Training - SLURM vs. Pytorch Built-In

### ISSUE THREAD

**Issue by todpole3** [facebookresearch/XLM#181]
We were able to do multi-node training of XLM using `python -m torch.distributed.launch` without SLURM. 

I wonder if you have compared the performance of `python -m torch.distributed.launch` and SLURM. Does SLURM simply gives additional experiment management function or does it also improve performance (in terms of training speed and model quality)?

**Comment by glample** [comment]
No it should not make any difference. But SLURM is easier to use because it takes care of multi-node training, while otherwise you have to manually specify the master node IP and run multiple start commands (one on each node). For single node training, SLURM does not add much compared to `torch.distributed.launch`

**Comment by todpole3** [comment]
Thanks.

**Comment by netw0rkf10w** [comment]
@todpole3 Could you please share the steps you did to make multi-node training work using `python -m torch.distributed.launch`? Thank you very much in advance!
