### ISSUE TITLE
Multi-GPU training not working

### ISSUE THREAD

**Issue by gbcolborne** [facebookresearch/XLM#67]
I am trying to pretrain using 4 GPUs, but I just get 4 processes running on the same GPU. My command looks like:

```
export CUDA_VISIBLE_DEVICES=0,1,2,3
export NGPU=4
python -m torch.distributed.launch --nproc_per_node=$NGPU train.py --exp_name pretrain --exp_id 01 --dump_path /path/to/dump --data_path /path/to/data --save_periodic 1 --lgs 'en-hi' --clm_steps '' --mlm_steps 'en,hi' --max_vocab -1 --min_count 0 --emb_dim 1024 --n_layers 12 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --encoder_only true --bptt 256 --max_len 100 --batch_size 4 --tokens_per_batch -1 --max_batch_size 0 --group_by_size true --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001,weight_decay=0 --epoch_size 200000 --validation_metrics _valid_mlm_ppl --stopping_criterion _valid_mlm_ppl,10 --lg_sampling_factor 0.7 --word_shuffle 0 --word_dropout 0 --word_blank 0 --eval_only false --local_rank -1 --master_port -1
```

The beginning of the output (when we initialize the distributed mode) looks like this:

```
SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : XXX
SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : XXX
SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : XXX
SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : XXX
```

Any ideas?

Edit: Do I have to install Slurm first? This was not mentioned in the requirements...

**Comment by glample** [comment]
No you can run it without SLURM. You set `--local_rank -1`, can you try to leave it not initialized? This value is handled by the torch.distributed.launch utility.

**Comment by gbcolborne** [comment]
Solved. I can now train on multiple GPUs. 

I seem to be limited to a batch size around 8 even though I have 12 GB of ram on each GPU, but that's a separate issue I will have to investigate. 

Thanks for your help.

**Comment by BinWone** [comment]
> Solved. I can now train on multiple GPUs.
> 
> I seem to be limited to a batch size around 8 even though I have 12 GB of ram on each GPU, but that's a separate issue I will have to investigate.
> 
> Thanks for your help.

i encounter the same question.
how do you solved this problem? help

**Comment by glample** [comment]
@BinWone you should never have to provide the `--local_rank` parameter, PyTorch distributed launcher will take care of this.

**Comment by fallcat** [comment]
When I'm using slurm, do I still need to use `torch.distributed.launch`? It makes my params.local_rank not -1 but in `src/slurm.py` it requires params.local_rank to be -1.

But when I didn't use `torch.distributed.launch`, it only runs on one GPU even though I requested 2 GPUs.

This is my current script:
`#!/bin/bash
#SBATCH --job-name=u-enfr
#SBATCH --ntasks-per-node=2
#SBATCH --mem=64GB
#SBATCH -d singleton
#SBATCH --open-mode append
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:p100:2
#SBATCH --partition=isi
#SBATCH -o exp/unmt_enfr/output_train.txt
#SBATCH --mail-type=ALL

export NGPU=2; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py \
--exp_name unsupMT_enfr \
--dump_path ./exp/unmt_enfr \
--reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' \
--data_path ./data/processed/en-fr/ \
--lgs 'en-fr'   \
--ae_steps 'en,fr'  \
--bt_steps 'en-fr-en,fr-en-fr' \
--word_shuffle 3   \
--word_dropout 0.1  \
--word_blank 0.1  \
--lambda_ae '0:1,100000:0.1,300000:0' \
--encoder_only false \
--emb_dim 1024  \
--n_layers 6  \
--n_heads 8   \
--dropout 0.1   \
--attention_dropout 0.1 \
--gelu_activation true  \
--tokens_per_batch 2000   \
--batch_size 32  \
--bptt 256 \
--optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001  \
--epoch_size 200000  \
--eval_bleu true  \
--stopping_criterion 'valid_en-fr_mt_bleu,10'  \
--validation_metrics 'valid_en-fr_mt_bleu'`

and this is the error I got:
`Traceback (most recent call last):
  File "train.py", line 327, in <module>
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 221, in main
    main(params)
  File "train.py", line 221, in main
    init_distributed_mode(params)
  File "/(file path)/XLM/src/slurm.py", line 62, in init_distributed_mode
    init_distributed_mode(params)
  File "/(file path)/XLM/src/slurm.py", line 62, in init_distributed_mode
    assert params.local_rank == -1   # on the cluster, this is handled by SLURM
AssertionError
    assert params.local_rank == -1   # on the cluster, this is handled by SLURM
AssertionError`

I tried to print out and `params.local_rank` turns out to be 0 and 1.
