### ISSUE TITLE
some questions about vocab and codec for XNLI

### ISSUE THREAD

**Issue by dupanfei1** [facebookresearch/XLM#85]
Hi, 
Thanks for your paper and code. I have several questions about the vocab and codec for XNLI.  
I want to do classification for japanese corpus. Does the vocab vocab_xnli_15 contain japanese bpe?  I find some common japanese words in vocab_xnli_15, but I don't find any japanese in  codes_xnli_15. And what is the function of codes_xnli_15?
Thanks.

**Comment by glample** [comment]
Hi,

Unfortunately, Japanese is not part of XNLI. They may be some Japanese words in the vocab, but they are probably just here by accident because there were a few Japanese words present in another language. `codes_xnli_15` is the set of codes learned by fastBPE that needs to be applied to the input data in order to have the same input vocabulary.

**Comment by dupanfei1** [comment]
Fine, thanks very much for you reply.
