### ISSUE TITLE
Use XLM embeddings for sentence classification

### ISSUE THREAD

**Issue by simonefrancia** [facebookresearch/XLM#87]
Hi,
I would like to start from XLM embeddings in order to create a sentence classifier for NLP text.

In the last months we have built a sentence classifier starting from LASER cross-lingual embedding and we saw good results in task we have faced.
On the other hand we think that BERT embedding could improve our results and provide to us more contextual information inside the embedding, so we would like to build a new classifier for the same task using XLM.

What we would like to do is a transfer-learning starting from embeddings.
In LASER, when we got the embedding of a sentence, the embedding size was (1,1024) for every sentence, so the embedding was already a kind of semantical pooling of all the tokens inside the sentence, that is the result of the BiLSTM steps.
Here in BERT, every sentence inside a batch has in output the dimension (n_token, 1024), so I was thinking about what was the best method to put all these outputs together and do classification. ( tell me if I am wrong in something or you don't agree with me ) 

Do you think that RNNs network is the best choice for our purpose? 
Thanks

**Comment by glample** [comment]
Hi,

There are several options here. You could:
1) start from a pretrained XLM model and finetune on a sentence classification task, where you feed the classifier with the first hidden state of the transformer output
2) instead of the first hidden state, you can consider either a dimension-wise max-pooling, or a dimension-wise mean of the transformer output
3) instead of considering a classifier that takes as input single vectors, you can have a CNN classifier added on top of the transformer, that can handle an arbitrary number of vectors as input

I have not tried and I'm not sure what is best, but with finetuning it should be fast to try.

**Comment by simonefrancia** [comment]
Ok, thanks, I think I will try the first step.
I have a question about point 1.
Why do we take the first hidden state of transformer, instead of last hidden layer?

Second question:
what model structure would you recommend as first test for classification?

Thanks

**Comment by glample** [comment]
1) Because the last state will appear at different positions based on the sentence length, so this may confuse the model. In the first state, the position embedding 0 will be finetuned to tell the model that this is where the prediction has to be made.
2) Just a `nn.Linear(transformer_dim, n_classes)` should be fine.

**Comment by AiSingularity** [comment]
@glample I was trying XLM embeddings and it produces different embeddings for the same sentence every time it's run. Is there a reason for that?
